export type Platform = "steam" | "playstation" | "xbox";

export interface Game {
  id: string;
  title: string;
  image: string;
  platform: Platform;
  publisher: string;
  developer: string;
  releaseDate: string;
  genres: string[];
  tags: string[];
  description: string;
  originalPrice: number;
  currentPrice: number;
  discount: number;
  rating: number;
  isFree?: boolean;
  isNew?: boolean;
  isBestseller?: boolean;
}

const steam = (appid: number) =>
  `https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/header.jpg`;

export const GAMES: Game[] = [
  {
    id: "1",
    title: "Cyberpunk 2077",
    image: steam(1091500),
    platform: "steam",
    publisher: "CD PROJEKT RED",
    developer: "CD PROJEKT RED",
    releaseDate: "2020-12-10",
    genres: ["RPG", "Ação"],
    tags: ["Open World", "Cyberpunk"],
    description:
      "Cyberpunk 2077 é um RPG de ação e aventura em mundo aberto ambientado em Night City, uma megalópole obcecada por poder, glamour e modificações corporais. Você é V, um mercenário fora da lei em busca de um implante único, a chave para a imortalidade.",
    originalPrice: 199.9,
    currentPrice: 59.97,
    discount: 70,
    rating: 4.6,
    isBestseller: true,
  },
  {
    id: "2",
    title: "Elden Ring",
    image: steam(1245620),
    platform: "playstation",
    publisher: "Bandai Namco",
    developer: "FromSoftware",
    releaseDate: "2022-02-25",
    genres: ["RPG", "Ação"],
    tags: ["Souls-like", "Fantasia"],
    description:
      "Um RPG de ação e fantasia épica em um vasto mundo aberto, onde os jogadores exploram as Terras Intermédias para se tornar o Lorde Prístino. Criado em colaboração entre Hidetaka Miyazaki e George R. R. Martin.",
    originalPrice: 249.9,
    currentPrice: 124.95,
    discount: 50,
    rating: 4.9,
    isBestseller: true,
  },
  {
    id: "3",
    title: "Halo Infinite",
    image: steam(1240440),
    platform: "xbox",
    publisher: "Xbox Game Studios",
    developer: "343 Industries",
    releaseDate: "2021-12-08",
    genres: ["FPS", "Ação"],
    tags: ["Sci-Fi", "Coop"],
    description:
      "Quando toda a esperança está perdida e o destino da humanidade está em jogo, o Master Chief está pronto para enfrentar o inimigo mais implacável já visto. Embarque na campanha lendária e no multiplayer free-to-play da série Halo.",
    originalPrice: 199.9,
    currentPrice: 79.96,
    discount: 60,
    rating: 4.4,
    isBestseller: true,
  },
  {
    id: "4",
    title: "Forza Horizon 5",
    image: steam(1551360),
    platform: "xbox",
    publisher: "Xbox Game Studios",
    developer: "Playground Games",
    releaseDate: "2021-11-09",
    genres: ["Corrida"],
    tags: ["Arcade", "Open World"],
    description:
      "Sua maior aventura Horizon te espera! Explore as paisagens vibrantes e em constante evolução do México com uma diversidade sem limites em centenas dos maiores carros do mundo.",
    originalPrice: 249.9,
    currentPrice: 74.97,
    discount: 70,
    rating: 4.7,
  },
  {
    id: "5",
    title: "Counter-Strike 2",
    image: steam(730),
    platform: "steam",
    publisher: "Valve",
    developer: "Valve",
    releaseDate: "2023-09-27",
    genres: ["FPS", "Ação"],
    tags: ["Competitivo", "Multiplayer"],
    description:
      "Por mais de duas décadas, Counter-Strike ofereceu uma experiência de tiro competitiva incomparável. Agora, o próximo capítulo da série CS chegou, marcando o maior salto tecnológico da franquia.",
    originalPrice: 0,
    currentPrice: 0,
    discount: 100,
    rating: 4.5,
    isFree: true,
  },
  {
    id: "6",
    title: "God of War Ragnarök",
    image: steam(2322010),
    platform: "playstation",
    publisher: "Sony Interactive",
    developer: "Santa Monica Studio",
    releaseDate: "2022-11-09",
    genres: ["Ação", "Aventura"],
    tags: ["História", "Mitologia"],
    description:
      "Embarque em uma jornada épica e emocionante enquanto Kratos e Atreus lutam para se manterem juntos ao se prepararem para o Ragnarök, o profetizado fim do mundo dos Nove Reinos da mitologia nórdica.",
    originalPrice: 299.9,
    currentPrice: 149.95,
    discount: 50,
    rating: 4.9,
  },
  {
    id: "7",
    title: "Gears 5",
    image: steam(1097840),
    platform: "xbox",
    publisher: "Xbox Game Studios",
    developer: "The Coalition",
    releaseDate: "2019-09-10",
    genres: ["TPS", "Ação"],
    tags: ["Coop", "Sci-Fi"],
    description:
      "Com o mundo à beira do colapso, Kait Diaz precisa desvendar as origens dos Locust e enfrentar uma ameaça pessoal. Jogue sozinho ou com um amigo em cooperação local e online.",
    originalPrice: 149.9,
    currentPrice: 29.98,
    discount: 80,
    rating: 4.5,
  },
  {
    id: "8",
    title: "Hades",
    image: steam(1145360),
    platform: "steam",
    publisher: "Supergiant Games",
    developer: "Supergiant Games",
    releaseDate: "2020-09-17",
    genres: ["Indie", "Roguelike"],
    tags: ["Ação", "Mitologia"],
    description:
      "Desafie o deus dos mortos enquanto luta para sair do Submundo neste roguelike de ação aclamado da Supergiant, criadora de Bastion, Transistor e Pyre.",
    originalPrice: 79.99,
    currentPrice: 23.99,
    discount: 70,
    rating: 4.8,
    isNew: true,
  },
  {
    id: "9",
    title: "The Last of Us Part I",
    image: steam(1888930),
    platform: "playstation",
    publisher: "Sony Interactive",
    developer: "Naughty Dog",
    releaseDate: "2023-03-28",
    genres: ["Ação", "Aventura"],
    tags: ["Narrativo", "Suspense"],
    description:
      "Vivencie a emocionante história e os personagens inesquecíveis em The Last of Us, ganhador de mais de 200 prêmios de Jogo do Ano, agora reconstruído do zero para o PC e o PlayStation 5.",
    originalPrice: 349.9,
    currentPrice: 174.95,
    discount: 50,
    rating: 4.7,
  },
  {
    id: "10",
    title: "Sea of Thieves",
    image: steam(1172620),
    platform: "xbox",
    publisher: "Xbox Game Studios",
    developer: "Rare",
    releaseDate: "2020-06-03",
    genres: ["Aventura", "Ação"],
    tags: ["Multiplayer", "Piratas"],
    description:
      "Sea of Thieves é a definitiva aventura pirata multiplayer, repleta de tesouros incalculáveis, batalhas navais épicas e infinitas histórias para contar sobre suas façanhas nos sete mares.",
    originalPrice: 199.9,
    currentPrice: 139.93,
    discount: 30,
    rating: 4.4,
    isNew: true,
  },
  {
    id: "11",
    title: "Baldur's Gate 3",
    image: steam(1086940),
    platform: "steam",
    publisher: "Larian Studios",
    developer: "Larian Studios",
    releaseDate: "2023-08-03",
    genres: ["RPG", "Estratégia"],
    tags: ["Coop", "Fantasia"],
    description:
      "Reúna seu grupo e volte aos Reinos Esquecidos em uma história de camaradagem e traição, sobrevivência e sacrifício, e a atração do poder absoluto. Baseado no sistema D&D 5e.",
    originalPrice: 199.9,
    currentPrice: 159.92,
    discount: 20,
    rating: 4.9,
    isNew: true,
  },
  {
    id: "12",
    title: "Destiny 2",
    image: steam(1085660),
    platform: "steam",
    publisher: "Bungie",
    developer: "Bungie",
    releaseDate: "2019-10-01",
    genres: ["FPS", "MMO"],
    tags: ["Sci-Fi", "Coop"],
    description:
      "Destiny 2 é um jogo de tiro em primeira pessoa multiplayer online gratuito. Mergulhe nos mundos mitológicos da nossa galáxia, forje amizades e conquiste o Sistema Solar ao lado dos seus amigos.",
    originalPrice: 0,
    currentPrice: 0,
    discount: 100,
    rating: 4.3,
    isFree: true,
  },
  {
    id: "13",
    title: "Red Dead Redemption 2",
    image: steam(1174180),
    platform: "steam",
    publisher: "Rockstar Games",
    developer: "Rockstar Games",
    releaseDate: "2019-12-05",
    genres: ["Ação", "Aventura"],
    tags: ["Open World", "Faroeste"],
    description:
      "Vencedor de mais de 175 prêmios de Jogo do Ano, Red Dead Redemption 2 é a saga épica de Arthur Morgan e da gangue Van der Linde enquanto fogem pela América em 1899. Uma vasta e atmosférica experiência que também serve de base para o Red Dead Online.",
    originalPrice: 239.9,
    currentPrice: 71.97,
    discount: 70,
    rating: 4.9,
    isBestseller: true,
  },
  {
    id: "14",
    title: "Grand Theft Auto V",
    image: steam(271590),
    platform: "steam",
    publisher: "Rockstar Games",
    developer: "Rockstar Games",
    releaseDate: "2015-04-14",
    genres: ["Ação", "Aventura"],
    tags: ["Open World", "Multiplayer"],
    description:
      "Quando um jovem golpista das ruas, um assaltante de banco aposentado e um psicopata aterrorizante se envolvem com alguns dos criminosos mais assustadores e desequilibrados do submundo, precisam realizar uma série de golpes ousados para sobreviver na implacável cidade de Los Santos.",
    originalPrice: 119.9,
    currentPrice: 35.97,
    discount: 70,
    rating: 4.7,
  },
  {
    id: "15",
    title: "The Witcher 3: Wild Hunt",
    image: steam(292030),
    platform: "steam",
    publisher: "CD PROJEKT RED",
    developer: "CD PROJEKT RED",
    releaseDate: "2015-05-18",
    genres: ["RPG", "Ação"],
    tags: ["Open World", "Fantasia"],
    description:
      "Você é Geralt de Rívia, um caçador de monstros mercenário. Diante de você está um continente devastado pela guerra, infestado por monstros de todos os tipos, para explorar à vontade. Sua missão atual? Encontrar a filha da profecia, uma jovem viva com o poder de mudar o mundo.",
    originalPrice: 79.99,
    currentPrice: 15.99,
    discount: 80,
    rating: 4.9,
  },
  {
    id: "16",
    title: "Hogwarts Legacy",
    image: steam(990080),
    platform: "playstation",
    publisher: "Warner Bros. Games",
    developer: "Avalanche Software",
    releaseDate: "2023-02-10",
    genres: ["RPG", "Ação"],
    tags: ["Open World", "Fantasia"],
    description:
      "Hogwarts Legacy é um RPG de ação em mundo aberto imersivo ambientado no mundo apresentado pela primeira vez nos livros de Harry Potter. Embarque em uma jornada através de locais familiares e novos enquanto explora e descobre animais fantásticos, personaliza seu bruxo e domina a arte da magia.",
    originalPrice: 249.9,
    currentPrice: 124.95,
    discount: 50,
    rating: 4.6,
    isBestseller: true,
  },
  {
    id: "17",
    title: "Starfield",
    image: steam(1716740),
    platform: "xbox",
    publisher: "Bethesda Softworks",
    developer: "Bethesda Game Studios",
    releaseDate: "2023-09-06",
    genres: ["RPG", "Aventura"],
    tags: ["Sci-Fi", "Open World"],
    description:
      "Starfield é o primeiro novo universo em 25 anos da Bethesda Game Studios, criadores de The Elder Scrolls V: Skyrim e Fallout 4. Nesta próxima geração de RPG de mundo aberto, ambientado em meio às estrelas, crie qualquer personagem que desejar e explore com liberdade sem precedentes.",
    originalPrice: 349.9,
    currentPrice: 174.95,
    discount: 50,
    rating: 4.2,
    isNew: true,
  },
  {
    id: "18",
    title: "Spider-Man Remastered",
    image: steam(1817070),
    platform: "playstation",
    publisher: "PlayStation PC LLC",
    developer: "Insomniac Games",
    releaseDate: "2022-08-12",
    genres: ["Ação", "Aventura"],
    tags: ["Super-herói", "Open World"],
    description:
      "Alcance grandes alturas em Marvel's Spider-Man Remastered. Peter Parker experiente enfrenta os maiores vilões enquanto tenta equilibrar sua vida caótica, seu relacionamento e salvar Nova York. Balance-se, salte e use a Web-Slinging em detalhes deslumbrantes.",
    originalPrice: 249.9,
    currentPrice: 99.96,
    discount: 60,
    rating: 4.8,
  },
  {
    id: "19",
    title: "Resident Evil 4",
    image: steam(2050650),
    platform: "steam",
    publisher: "Capcom",
    developer: "Capcom",
    releaseDate: "2023-03-24",
    genres: ["Ação", "Terror"],
    tags: ["Survival Horror", "Remake"],
    description:
      "Sobrevivência é apenas o começo. Seis anos se passaram desde o desastre biológico em Raccoon City. O agente Leon S. Kennedy, um dos sobreviventes, foi enviado para resgatar a filha sequestrada do presidente. Ele consegue rastreá-la a uma vila europeia isolada, onde há algo terrivelmente errado com os moradores.",
    originalPrice: 249.9,
    currentPrice: 99.96,
    discount: 60,
    rating: 4.9,
    isBestseller: true,
  },
  {
    id: "20",
    title: "Dota 2",
    image: steam(570),
    platform: "steam",
    publisher: "Valve",
    developer: "Valve",
    releaseDate: "2013-07-09",
    genres: ["MOBA", "Estratégia"],
    tags: ["Competitivo", "Free to Play"],
    description:
      "Todos os dias, milhões de jogadores em todo o mundo entram em batalha como um dos mais de cem heróis de Dota. É um jogo profundo com centenas de horas de história em construção — e a única maneira de aprender é jogando.",
    originalPrice: 0,
    currentPrice: 0,
    discount: 100,
    rating: 4.4,
    isFree: true,
  },
];

export const PLATFORM_LABELS: Record<Platform, string> = {
  steam: "Steam",
  playstation: "PlayStation",
  xbox: "Xbox",
};
