export type Platform = "steam" | "playstation" | "xbox";

export interface Game {
  id: string;
  title: string;
  image: string;
  platform: Platform;
  publisher: string;
  developer: string;
  releaseDate: string;
  genres: string[];
  tags: string[];
  originalPrice: number;
  currentPrice: number;
  discount: number;
  rating: number;
  isFree?: boolean;
  isNew?: boolean;
  isBestseller?: boolean;
}

const img = (seed: string, w = 800, h = 450) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}/${w}/${h}`;

export const GAMES: Game[] = [
  {
    id: "1",
    title: "Cyber Nexus 2088",
    image: img("cybernexus"),
    platform: "steam",
    publisher: "NeonWorks",
    developer: "Pulse Studio",
    releaseDate: "2024-11-12",
    genres: ["RPG", "Ação"],
    tags: ["Open World", "Cyberpunk"],
    originalPrice: 299.9,
    currentPrice: 89.9,
    discount: 70,
    rating: 4.7,
    isBestseller: true,
  },
  {
    id: "2",
    title: "Shadow Realm: Ascension",
    image: img("shadowrealm"),
    platform: "playstation",
    publisher: "Umbra Games",
    developer: "Umbra Studio",
    releaseDate: "2025-02-20",
    genres: ["RPG", "Ação"],
    tags: ["Souls-like", "Fantasia"],
    originalPrice: 349.9,
    currentPrice: 174.95,
    discount: 50,
    rating: 4.9,
    isNew: true,
  },
  {
    id: "3",
    title: "Halo: Infinite Legacy",
    image: img("halolegacy"),
    platform: "xbox",
    publisher: "Xbox Game Studios",
    developer: "343 Industries",
    releaseDate: "2024-06-10",
    genres: ["FPS", "Ação"],
    tags: ["Sci-Fi", "Coop"],
    originalPrice: 249.9,
    currentPrice: 99.96,
    discount: 60,
    rating: 4.5,
    isBestseller: true,
  },
  {
    id: "4",
    title: "Velocity Circuit",
    image: img("velocity"),
    platform: "steam",
    publisher: "TurboSoft",
    developer: "Redline",
    releaseDate: "2025-01-08",
    genres: ["Corrida"],
    tags: ["Arcade", "Multiplayer"],
    originalPrice: 199.9,
    currentPrice: 59.97,
    discount: 70,
    rating: 4.3,
  },
  {
    id: "5",
    title: "Whispering Woods",
    image: img("whisperwoods"),
    platform: "steam",
    publisher: "Lumen",
    developer: "Firefly Games",
    releaseDate: "2025-03-01",
    genres: ["Indie", "Aventura"],
    tags: ["Atmosférico", "Narrativo"],
    originalPrice: 79.9,
    currentPrice: 0,
    discount: 100,
    rating: 4.6,
    isFree: true,
  },
  {
    id: "6",
    title: "Frostbound: Survival",
    image: img("frostbound"),
    platform: "playstation",
    publisher: "IceForge",
    developer: "Northlight",
    releaseDate: "2024-09-14",
    genres: ["Sobrevivência", "Terror"],
    tags: ["Crafting", "Multiplayer"],
    originalPrice: 229.9,
    currentPrice: 91.96,
    discount: 60,
    rating: 4.4,
  },
  {
    id: "7",
    title: "Iron Battalion 1",
    image: img("ironbattalion"),
    platform: "xbox",
    publisher: "Steel Ops",
    developer: "Bastion Interactive",
    releaseDate: "2024-08-22",
    genres: ["Estratégia", "Ação"],
    tags: ["Guerra", "Tático"],
    originalPrice: 189.9,
    currentPrice: 75.96,
    discount: 60,
    rating: 4.2,
  },
  {
    id: "8",
    title: "Neon Drift Arena",
    image: img("neondrift"),
    platform: "steam",
    publisher: "PulseWave",
    developer: "Arcade Kings",
    releaseDate: "2025-04-11",
    genres: ["Corrida", "Indie"],
    tags: ["Retro", "Synthwave"],
    originalPrice: 89.9,
    currentPrice: 26.97,
    discount: 70,
    rating: 4.8,
    isNew: true,
  },
  {
    id: "9",
    title: "Abyssal Depths",
    image: img("abyssal"),
    platform: "playstation",
    publisher: "Deepblue",
    developer: "Tide Studio",
    releaseDate: "2024-05-03",
    genres: ["Terror", "Aventura"],
    tags: ["VR", "Suspense"],
    originalPrice: 259.9,
    currentPrice: 129.95,
    discount: 50,
    rating: 4.5,
  },
  {
    id: "10",
    title: "Skybreaker: Realms",
    image: img("skybreaker"),
    platform: "xbox",
    publisher: "Aether Games",
    developer: "Skywing",
    releaseDate: "2025-05-19",
    genres: ["RPG", "Aventura"],
    tags: ["Fantasia", "Open World"],
    originalPrice: 279.9,
    currentPrice: 195.93,
    discount: 30,
    rating: 4.6,
    isNew: true,
  },
  {
    id: "11",
    title: "Tactical Ops 7",
    image: img("tacticalops"),
    platform: "steam",
    publisher: "BlackOps Studios",
    developer: "Shadow Team",
    releaseDate: "2024-10-01",
    genres: ["FPS", "Estratégia"],
    tags: ["Coop", "Multiplayer"],
    originalPrice: 219.9,
    currentPrice: 43.98,
    discount: 80,
    rating: 4.4,
  },
  {
    id: "12",
    title: "Little Sprout",
    image: img("littlesprout"),
    platform: "steam",
    publisher: "GreenLeaf",
    developer: "Tiny Garden",
    releaseDate: "2025-02-14",
    genres: ["Indie"],
    tags: ["Relaxante", "Casual"],
    originalPrice: 49.9,
    currentPrice: 0,
    discount: 100,
    rating: 4.7,
    isFree: true,
  },
];

export const PLATFORM_LABELS: Record<Platform, string> = {
  steam: "Steam",
  playstation: "PlayStation",
  xbox: "Xbox",
};
